### ISSUE TITLE
instructions/documentation?

### ISSUE THREAD

**Issue by sebastianbhahn** [TheStolenBattenberg/ToolsForKFIV#7]

**Comment by TheStolenBattenberg** [comment]
The tools currently provided are mostly for research purposes into FromSofts proprietary formats, to enable proper extraction and conversion and understanding.

Documentation is planned to be written, but the tools are gonna change a lot before then.

For now, I'll say that they're as simple as possible command line applications. Just drag the file onto the exe and boom, it's converted/extracted.
