### ISSUE TITLE
exe does nothing

### ISSUE THREAD

**Issue by sebastianbhahn** [TheStolenBattenberg/ToolsForKFIV#9]
Tried the three latest precompiled releases. Made sure the VS redistributible was installed. Click the exe. Nothing happens.

**Comment by sebastianbhahn** [comment]
update: all but the most recent release work with netcore installed. Precompiles don't include the readme that's in the source.
The most recent release throws an error at file resource\prettynames.csv
unhandled exception. (line: 23, col: 1, idk: 223) - (line: 23, col: 2, idk: 224)
while parsing a block mapping, did not find expected key.

**Comment by TheStolenBattenberg** [comment]
The latest release has a small issue with the configuration file. Before pushing it I'd accidently added an additional symbol to the end of the file. If you'd like to use the most recent build, simply delete the configuration file (_configuration.yaml_) and it will create a new one.
